server:
  port: 5555

spring:
  activemq:
    broker-url: tcp://192.168.75.134:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true #false代表队列  true代表Topic

#自己定义队列名称
myTopic: boot_activemq_topic